spring:
  application:
    name: Task21
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 231514
  jpa:
    hibernate:
      ddl-auto: create
  mail:
    host: smtp.yandex.com
    port: 465
    protocol: smtps
    username: bokgosha@yandex.ru
    password: qtxselgtcdgeljsm
